server:
  port: 8083

spring:
  application:
    name: Restaurant-Management-System

  datasource:
    url: jdbc:postgresql://103.133.215.182:5432/gloitel_db_rms
    username: gloitel
    password: gloitel123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  # secret: asxhsys-hdshghdhjd-hgdshdikeudgbck-agdsfeyj-bdgdhsjkslk--hshdjsdo-jfdkfirhy
  secret: asxhsys-hdshghdhjd-hgdshdikeudgbck-agdsfeyj-bdgdhsjkslk--hshdjsdo-jfdkfirhy
  access-token-validity: 43200000 # 12 hours in milliseconds
  refresh-token-validity: 604800000 # 7 days in milliseconds
